---

# Add OSE 3.2 required repositories
- name: Add RHEL 7 base and OSE 3.2 repos
  command: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.2-rpms"

# Comment out these lines in case Atomic Host
#- name: Install required packages
#  yum: pkg={{item}} state=installed
#  with_items:
#    - vim
#    - wget
#    - git
#    - net-tools
#    - mlocate
#    - bind-utils
#    - iptables-services
#    - bridge-utils
#    - bash-completion
#    - atomic-openshift-utils
#    - docker-1.10.3
